<a href="https://colab.research.google.com/github/pandeeswar/phishing_dataset/blob/main/lstm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import re
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from sklearn.model_selection import train_test_split
from google.colab import files


uploaded = files.upload()


Saving ph.csv to ph.csv


In [ ]:
# Load the dataset from the CSV file
data = pd.read_csv('ph.csv')

In [ ]:
# Extract the URLs from the dataset
urls = data['url'].values
print(urls)


['http://www.crestonwood.com/router.php'
 'http://shadetreetechnology.com/V4/validation/a111aedc8ae390eabcfa130e041a10a4'
 'https://support-appleld.com.secureupdate.duilawyeryork.com/ap/89e6a3b4b063b8d/?cmd=_update&dispatch=89e6a3b4b063b8d1b&locale=_'
 ...
 'https://www.facebook.com/Interactive-Television-Pvt-Ltd-Group-M-100230523435650/photos/?ref=page_internal'
 'http://www.mypublicdomainpictures.com/'
 'http://174.139.46.123/ap/signin?openid.pape.max_auth_age=0&amp;openid.return_to=https%3A%2F%2Fwww.amazon.co.jp%2F%3Fref_%3Dnav_em_hd_re_signin&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.assoc_handle=jpflex&amp;openid.mode=checkid_setup&amp;key=a@b.c&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;&amp;ref_=nav_em_hd_clc_signin']


In [ ]:
# Preprocess the URLs by tokenizing and padding them to a fixed length
tokenizer = Tokenizer()
tokenizer.fit_on_texts(urls)
sequences = tokenizer.texts_to_sequences(urls)
max_length = max(len(seq) for seq in sequences)
padded_sequences = pad_sequences(sequences, maxlen=max_length, padding='post')
print(padded_sequences)

[[    2     3  5508 ...     0     0     0]
 [    2   136     1 ...     0     0     0]
 [    4    29    22 ...     0     0     0]
 ...
 [    4     3   112 ...     0     0     0]
 [    2     3 20542 ...     0     0     0]
 [    2  1063  1654 ...     0     0     0]]


In [ ]:
# Split the dataset into training and testing sets
labels = data['label'].values
X_train, X_test, y_train, y_test = train_test_split(padded_sequences, labels, test_size=0.2, random_state=42)



In [ ]:
 
model = Sequential()
model.add(Embedding(len(tokenizer.word_index) + 1, 64, input_length=max_length))
model.add(LSTM(64, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 109, 64)           1314752   
                                                                 
 lstm_2 (LSTM)               (None, 64)                33024     
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 1,347,841
Trainable params: 1,347,841
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


In [ ]:
# Train the LSTM model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=32)


Epoch 1/10


UnimplementedError: ignored

In [ ]:
# Use the trained LSTM model to predict the labels of the URLs in the dataset
y_pred = model.predict(padded_sequences)

358/358 [==============================] - 5s 14ms/step


In [ ]:
# Extract the hyperlinks from the phishing URLs and print them
for i in range(len(urls)):
    if y_pred[i] > 0.5:
        match = re.findall(r'(https?://\S+)', urls[i])
        if match:
            print(f"Phishing URL: {urls[i]}")
            print(f"Hyperlink: {match[0]}\n")

Streaming output truncated to the last 5000 lines.
Hyperlink: http://cdek-pay.ru.com

Phishing URL: https://www.gotquestions.org/Noble-Eightfold-Path.html
Hyperlink: https://www.gotquestions.org/Noble-Eightfold-Path.html

Phishing URL: http://www.inetservicescloud.com/knowledgebase/how-to-disable-ctrl-alt-del-in-centos6rhel6/
Hyperlink: http://www.inetservicescloud.com/knowledgebase/how-to-disable-ctrl-alt-del-in-centos6rhel6/

Phishing URL: https://openmodelica.org/home/consortium
Hyperlink: https://openmodelica.org/home/consortium

Phishing URL: http://server.main.login.support.hotwills.com.au
Hyperlink: http://server.main.login.support.hotwills.com.au

Phishing URL: https://bancolombia-webs.webcindario.com/VALIDATEPASSWORDscisCjbTnfpNmVKQgeSUxnzRLmBdbq2BSLvH8jz8T1eNjJrxD2uact4fC1fGWN1VgTRClno-back-button.html
Hyperlink: https://bancolombia-webs.webcindario.com/VALIDATEPASSWORDscisCjbTnfpNmVKQgeSUxnzRLmBdbq2BSLvH8jz8T1eNjJrxD2uact4fC1fGWN1VgTRClno-back-button.html

Phishing URL: http